cookie:
    expiry_days: 30
    name: your_app_cookie
credentials:
    usernames:
        # Example user (replace with real users later or use registration)
        testuser:
            email: test@example.com
            name: Test User
            password: ${{$2b$12$Eom6SjPVFjmlctPpD/DXTeP93ICWAiZFLl/plj4sfGdZ090OGS9/q}} # You'll generate this